#!/usr/bin/env python
"""
pycallgraph
This script is the command line interface to the pycallgraph Python library.

See http://pycallgraph.slowchop.com/ for more information.
"""
import pycallgraph


pycg_cli = pycallgraph.CommandLine()
pycg_cli.parse_args()

globals()['__file__'] = pycg_cli.config.command

file_content = open(pycg_cli.config.command).read()

with pycg_cli.run():
    exec(file_content)
