#!/usr/bin/env python
"""
pycallgraph
This script is the command line interface to the pycallgraph Python library.

See https://pycallgraph.slowchop.com/ for more information.
"""
import pycallgraph as __pycallgraph


__config = __pycallgraph.Config()
__config.parse_args()

globals()['__file__'] = __config.command

__file_content = open(__config.command).read()

with __pycallgraph.PyCallGraph(config=__config):
    exec(__file_content)
